resolver: lts-10.10

packages:
- '.'

extra-deps:
  - bits-extra-0.0.1.2
  - hedgehog-0.6
  - hw-prim-0.6.2.0
  - hw-rankselect-base-0.3.2.0
  - hw-rankselect-0.12.0.2

flags: {}

extra-package-dbs: []
