version: 2.1

orbs:
  haskell: haskell-works/haskell-build@dev:1.3.0
  github: haskell-works/github-release@1.0.1
  hackage: haskell-works/hackage@1.0.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build:
          name: Build with GHC 8.4.4
          executor: haskell/ghc-8_4_4

      - haskell/build:
          name: Build with GHC 8.6.3
          executor: haskell/ghc-8_6_3

      - github/release-cabal:
          name: GitHub Release
          requires:
            - Build with GHC 8.4.4
            - Build with GHC 8.6.3
          checkout: true
          cabal-file: hw-xml.cabal
          filters:
            branches:
              only: master

      - hackage/upload:
          publish: true
          requires:
            - GitHub Release
          username: ${HACKAGE_USER}
          password: ${HACKAGE_PASS}
